package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUploadinfo<M extends BaseUploadinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAddress(java.lang.String address) {
		set("address", address);
	}
	
	public java.lang.String getAddress() {
		return getStr("address");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setDataTime(java.util.Date dataTime) {
		set("dataTime", dataTime);
	}
	
	public java.util.Date getDataTime() {
		return get("dataTime");
	}

	public void setLon(java.lang.String lon) {
		set("lon", lon);
	}
	
	public java.lang.String getLon() {
		return getStr("lon");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public void setPicturepath1(java.lang.String picturepath1) {
		set("picturepath1", picturepath1);
	}
	
	public java.lang.String getPicturepath1() {
		return getStr("picturepath1");
	}

	public void setRemessage(java.lang.String remessage) {
		set("remessage", remessage);
	}
	
	public java.lang.String getRemessage() {
		return getStr("remessage");
	}

	public void setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
	}
	
	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public void setVideopath1(java.lang.String videopath1) {
		set("videopath1", videopath1);
	}
	
	public java.lang.String getVideopath1() {
		return getStr("videopath1");
	}

	public void setLat(java.lang.String lat) {
		set("lat", lat);
	}
	
	public java.lang.String getLat() {
		return getStr("lat");
	}

	public void setClassfic(java.lang.Integer classfic) {
		set("classfic", classfic);
	}
	
	public java.lang.Integer getClassfic() {
		return getInt("classfic");
	}

	public void setPicturepath2(java.lang.String picturepath2) {
		set("picturepath2", picturepath2);
	}
	
	public java.lang.String getPicturepath2() {
		return getStr("picturepath2");
	}

	public void setWentidizhi(java.lang.String wentidizhi) {
		set("wentidizhi", wentidizhi);
	}
	
	public java.lang.String getWentidizhi() {
		return getStr("wentidizhi");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setRemessageMy(java.lang.String remessageMy) {
		set("remessageMy", remessageMy);
	}
	
	public java.lang.String getRemessageMy() {
		return getStr("remessageMy");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}
	
	public java.lang.Integer getStates() {
		return getInt("states");
	}

	public void setDealName(java.lang.String dealName) {
		set("dealName", dealName);
	}
	
	public java.lang.String getDealName() {
		return getStr("dealName");
	}

}
