package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMessage<M extends BaseMessage<M>> extends Model<M> implements IBean {

	public void setContent(java.lang.String content) {
		set("content", content);
	}
	
	public java.lang.String getContent() {
		return getStr("content");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setIsRead(java.lang.Boolean isRead) {
		set("isRead", isRead);
	}
	
	public java.lang.Boolean getIsRead() {
		return get("isRead");
	}

	public void setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
	}
	
	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	public void setReadTime(java.util.Date readTime) {
		set("read_time", readTime);
	}
	
	public java.util.Date getReadTime() {
		return get("read_time");
	}

	public void setSender(java.lang.String sender) {
		set("sender", sender);
	}
	
	public java.lang.String getSender() {
		return getStr("sender");
	}

	public void setReceiver(java.lang.String receiver) {
		set("receiver", receiver);
	}
	
	public java.lang.String getReceiver() {
		return getStr("receiver");
	}

	public void setTitle(java.lang.String title) {
		set("title", title);
	}
	
	public java.lang.String getTitle() {
		return getStr("title");
	}

}
