package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServeInfo<M extends BaseServeInfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInspectionItems(java.lang.String inspectionItems) {
		set("inspection_items", inspectionItems);
	}
	
	public java.lang.String getInspectionItems() {
		return getStr("inspection_items");
	}

	public void setAcceptanceStandard(java.lang.String acceptanceStandard) {
		set("acceptance_standard", acceptanceStandard);
	}
	
	public java.lang.String getAcceptanceStandard() {
		return getStr("acceptance_standard");
	}

	public void setType(java.lang.String type) {
		set("type", type);
	}
	
	public java.lang.String getType() {
		return getStr("type");
	}

}
