package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTestStBasis<M extends BaseTestStBasis<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setStandard(java.lang.String standard) {
		set("standard", standard);
	}
	
	public java.lang.String getStandard() {
		return getStr("standard");
	}

	public void setStandardNumber(java.lang.String standardNumber) {
		set("standard_number", standardNumber);
	}
	
	public java.lang.String getStandardNumber() {
		return getStr("standard_number");
	}

	public void setStandardName(java.lang.String standardName) {
		set("standard_name", standardName);
	}
	
	public java.lang.String getStandardName() {
		return getStr("standard_name");
	}

	public void setStandardFile(java.lang.String standardFile) {
		set("standard_file", standardFile);
	}
	
	public java.lang.String getStandardFile() {
		return getStr("standard_file");
	}

}
