package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUsername(java.lang.String username) {
		set("username", username);
	}
	
	public java.lang.String getUsername() {
		return getStr("username");
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("password");
	}

	public void setCompany(java.lang.String company) {
		set("company", company);
	}
	
	public java.lang.String getCompany() {
		return getStr("company");
	}

	public void setPowerPlantName(java.lang.String powerPlantName) {
		set("power_plant_name", powerPlantName);
	}
	
	public java.lang.String getPowerPlantName() {
		return getStr("power_plant_name");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setRid(java.lang.Integer rid) {
		set("rid", rid);
	}
	
	public java.lang.Integer getRid() {
		return getInt("rid");
	}

	public void setStates(java.lang.Integer states) {
		set("states", states);
	}
	
	public java.lang.Integer getStates() {
		return getInt("states");
	}

	public void setCreatTime(java.util.Date creatTime) {
		set("creat_time", creatTime);
	}
	
	public java.util.Date getCreatTime() {
		return get("creat_time");
	}

	public void setElectricity(java.lang.String electricity) {
		set("electricity", electricity);
	}
	
	public java.lang.String getElectricity() {
		return getStr("electricity");
	}

	public void setContactName(java.lang.String contactName) {
		set("contact_name", contactName);
	}
	
	public java.lang.String getContactName() {
		return getStr("contact_name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("phone");
	}

	public void setUnread(java.lang.Boolean unread) {
		set("unread", unread);
	}
	
	public java.lang.Boolean getUnread() {
		return get("unread");
	}

}
