package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWeixinuser<M extends BaseWeixinuser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setAccessToken(java.lang.String accessToken) {
		set("access_token", accessToken);
	}
	
	public java.lang.String getAccessToken() {
		return getStr("access_token");
	}

	public void setCity(java.lang.String city) {
		set("city", city);
	}
	
	public java.lang.String getCity() {
		return getStr("city");
	}

	public void setCountry(java.lang.String country) {
		set("country", country);
	}
	
	public java.lang.String getCountry() {
		return getStr("country");
	}

	public void setHeadimgurl(java.lang.String headimgurl) {
		set("headimgurl", headimgurl);
	}
	
	public java.lang.String getHeadimgurl() {
		return getStr("headimgurl");
	}

	public void setNickname(java.lang.String nickname) {
		set("nickname", nickname);
	}
	
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	public void setOpenid(java.lang.String openid) {
		set("openid", openid);
	}
	
	public java.lang.String getOpenid() {
		return getStr("openid");
	}

	public void setPrivilege(byte[] privilege) {
		set("privilege", privilege);
	}
	
	public byte[] getPrivilege() {
		return get("privilege");
	}

	public void setProvince(java.lang.String province) {
		set("province", province);
	}
	
	public java.lang.String getProvince() {
		return getStr("province");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("sex");
	}

	public void setUnionid(java.lang.String unionid) {
		set("unionid", unionid);
	}
	
	public java.lang.String getUnionid() {
		return getStr("unionid");
	}

	public void setCredit(java.lang.Long credit) {
		set("credit", credit);
	}
	
	public java.lang.Long getCredit() {
		return getLong("credit");
	}

}
