package com.demo.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseServeDetail<M extends BaseServeDetail<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public void setInfoId(java.lang.Integer infoId) {
		set("info_id", infoId);
	}
	
	public java.lang.Integer getInfoId() {
		return getInt("info_id");
	}

	public void setDetail(java.lang.String detail) {
		set("detail", detail);
	}
	
	public java.lang.String getDetail() {
		return getStr("detail");
	}

	public void setServeUserId(java.lang.Integer serveUserId) {
		set("serve_user_id", serveUserId);
	}
	
	public java.lang.Integer getServeUserId() {
		return getInt("serve_user_id");
	}

	public void setInspectionItems(java.lang.String inspectionItems) {
		set("inspection_items", inspectionItems);
	}
	
	public java.lang.String getInspectionItems() {
		return getStr("inspection_items");
	}

	public void setTime(java.util.Date time) {
		set("time", time);
	}
	
	public java.util.Date getTime() {
		return get("time");
	}

	public void setEditor(java.lang.String editor) {
		set("editor", editor);
	}
	
	public java.lang.String getEditor() {
		return getStr("editor");
	}

	public void setUploadRecordId(java.lang.Integer uploadRecordId) {
		set("upload_record_id", uploadRecordId);
	}
	
	public java.lang.Integer getUploadRecordId() {
		return getInt("upload_record_id");
	}

}
