package com.demo.common.model;

import com.demo.common.model.base.BaseBasicInfomation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BasicInfomation extends BaseBasicInfomation<BasicInfomation> {
	
}
