package com.demo.common.model;

import com.demo.common.model.base.BaseDetectionDevice;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DetectionDevice extends BaseDetectionDevice<DetectionDevice> {
	
}
