package com.demo.common.model;

import com.demo.common.model.base.BaseServeUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServeUser extends BaseServeUser<ServeUser> {
	
}
