package com.demo.common.model;

import com.demo.common.model.base.BaseServeInfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServeInfo extends BaseServeInfo<ServeInfo> {
	
}
