package com.demo.common.model;

import com.demo.common.model.base.BaseServeDetail;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ServeDetail extends BaseServeDetail<ServeDetail> {
	
}
