package com.demo.common.model;

import com.demo.common.model.base.BaseTableTemplate;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TableTemplate extends BaseTableTemplate<TableTemplate> {
	
}
