package com.demo.common.model;

import com.demo.common.model.base.BaseTestStBasis;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class TestStBasis extends BaseTestStBasis<TestStBasis> {
	
}
