package com.demo.common.model;

import com.demo.common.model.base.BaseUploadRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadRecord extends BaseUploadRecord<UploadRecord> {
	
}
