package com.demo.common.model;

import com.demo.common.model.base.BaseUploadinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Uploadinfo extends BaseUploadinfo<Uploadinfo> {
	
}
